package com.musicschool.musicschoolbackend.service;

import com.musicschool.musicschoolbackend.dto.InstrumentDTO;
import com.musicschool.musicschoolbackend.model.Instrument;
import com.musicschool.musicschoolbackend.repository.InstrumentRepository;
import jakarta.persistence.EntityExistsException;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class InstrumentService {

    private final InstrumentRepository instrumentRepository;

    public InstrumentService(InstrumentRepository instrumentRepository) {
        this.instrumentRepository = instrumentRepository;
    }

    // Converts Entity to DTO
    private InstrumentDTO toDTO(Instrument instrument) {
        return new InstrumentDTO(instrument.getId(), instrument.getName(), instrument.getDescription(), instrument.getIconUrl());
    }

    // Converts DTO to Entity (for creation or update)
    private Instrument toEntity(InstrumentDTO dto) {
        Instrument instrument = new Instrument();
        instrument.setId(dto.getId()); // Can be null for creation
        instrument.setName(dto.getName());
        instrument.setDescription(dto.getDescription());
        instrument.setIconUrl(dto.getIconUrl());
        return instrument;
    }

    @Transactional(readOnly = true)
    public List<InstrumentDTO> getAllInstruments() {
        return instrumentRepository.findAll().stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public InstrumentDTO getInstrumentById(Long id) {
        Instrument instrument = instrumentRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Instrument non trouvé avec l'ID: " + id));
        return toDTO(instrument);
    }

    @Transactional
    public InstrumentDTO createInstrument(InstrumentDTO instrumentDTO) {
        if (instrumentRepository.existsByName(instrumentDTO.getName())) {
            throw new EntityExistsException("Un instrument avec ce nom existe déjà: " + instrumentDTO.getName());
        }
        Instrument instrument = toEntity(instrumentDTO);
        instrument.setId(null); // Ensure ID is generated by DB
        return toDTO(instrumentRepository.save(instrument));
    }

    @Transactional
    public InstrumentDTO updateInstrument(Long id, InstrumentDTO instrumentDTO) {
        Instrument existingInstrument = instrumentRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Instrument non trouvé avec l'ID: " + id));

        // Check if the name has changed and if the new name already exists for another instrument
        if (!existingInstrument.getName().equals(instrumentDTO.getName()) && instrumentRepository.existsByName(instrumentDTO.getName())) {
            throw new EntityExistsException("Un autre instrument avec ce nom existe déjà: " + instrumentDTO.getName());
        }

        existingInstrument.setName(instrumentDTO.getName());
        existingInstrument.setDescription(instrumentDTO.getDescription());
        existingInstrument.setIconUrl(instrumentDTO.getIconUrl());

        return toDTO(instrumentRepository.save(existingInstrument));
    }

    @Transactional
    public void deleteInstrument(Long id) {
        if (!instrumentRepository.existsById(id)) {
            throw new EntityNotFoundException("Instrument non trouvé avec l'ID: " + id);
        }
        instrumentRepository.deleteById(id);
    }
}